/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gymapplication;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohammad Alqasem
 */
public class CoachJFrame extends GymApplication {

    /**
     * Creates new form CoachJFrame
     */
    public CoachJFrame() {
        initComponents();
            
        // أضف مستمع الأحداث لزر الدخول هنا
        
        loginCoach.addActionListener(e -> {
            // قم بتحديث المتغيرات من حقول النص قبل استدعاء الدالة login
            
            CoachID = EnterIDCoachForLogin.getText();
            Password = EnterPasswordCoachForLogin.getText();
            
         
            
                
             if (CoachID == null || CoachID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Coach ID.");
            return;
        }
        if (Password == null || Password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your password.");
            return;
        }
           login();
        });
        
    }
private String CoachID;
private String Password;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelLoginCoach = new javax.swing.JLabel();
        loginCoach = new java.awt.Button();
        backTOGymJFrame = new java.awt.Button();
        EnterIDCoachForLogin = new javax.swing.JTextField();
        LabelforIDCoach = new javax.swing.JLabel();
        LabelForCoachPassword = new javax.swing.JLabel();
        EnterPasswordCoachForLogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 57, 66));
        jPanel1.setForeground(new java.awt.Color(26, 41, 62));

        LabelLoginCoach.setBackground(new java.awt.Color(255, 255, 255));
        LabelLoginCoach.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LabelLoginCoach.setForeground(new java.awt.Color(255, 255, 255));
        LabelLoginCoach.setText("Login Coach");

        loginCoach.setActionCommand("Login_to_gym");
        loginCoach.setBackground(new java.awt.Color(203, 22, 45));
        loginCoach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginCoach.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        loginCoach.setForeground(new java.awt.Color(255, 255, 255));
        loginCoach.setLabel("Login");
        loginCoach.setName(""); // NOI18N
        loginCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginCoachActionPerformed(evt);
            }
        });

        backTOGymJFrame.setActionCommand("Back");
        backTOGymJFrame.setBackground(new java.awt.Color(203, 22, 45));
        backTOGymJFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backTOGymJFrame.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        backTOGymJFrame.setForeground(new java.awt.Color(255, 255, 255));
        backTOGymJFrame.setLabel("Back");
        backTOGymJFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backTOGymJFrameActionPerformed(evt);
            }
        });

        EnterIDCoachForLogin.setBackground(new java.awt.Color(110, 110, 111));
        EnterIDCoachForLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EnterIDCoachForLogin.setForeground(new java.awt.Color(255, 255, 255));
        EnterIDCoachForLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EnterIDCoachForLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterIDCoachForLoginActionPerformed(evt);
            }
        });

        LabelforIDCoach.setBackground(new java.awt.Color(110, 110, 111));
        LabelforIDCoach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelforIDCoach.setForeground(new java.awt.Color(255, 255, 255));
        LabelforIDCoach.setText("   ID Coach :");

        LabelForCoachPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelForCoachPassword.setForeground(new java.awt.Color(255, 255, 255));
        LabelForCoachPassword.setText("Password :");

        EnterPasswordCoachForLogin.setBackground(new java.awt.Color(110, 110, 111));
        EnterPasswordCoachForLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EnterPasswordCoachForLogin.setForeground(new java.awt.Color(255, 255, 255));
        EnterPasswordCoachForLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EnterPasswordCoachForLogin.setToolTipText("*");
        EnterPasswordCoachForLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterPasswordCoachForLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(LabelforIDCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(EnterIDCoachForLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(LabelForCoachPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(EnterPasswordCoachForLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelLoginCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(backTOGymJFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loginCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelLoginCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelforIDCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterIDCoachForLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelForCoachPassword)
                    .addComponent(EnterPasswordCoachForLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(loginCoach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(backTOGymJFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginCoachActionPerformed
        // TODO add your handling code here:
        /*

        if (CID == null || CID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Member ID.");
            return;
        }
        if (CPass == null || CPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your password.");
            return;
        }
        */

    }//GEN-LAST:event_loginCoachActionPerformed

    private void backTOGymJFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backTOGymJFrameActionPerformed
        // TODO add your handling code here:
       GYMJFrame Gym = new GYMJFrame();  
      Gym.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backTOGymJFrameActionPerformed

    private void EnterIDCoachForLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterIDCoachForLoginActionPerformed
        // TODO add your handling code here:
        CoachID = EnterIDCoachForLogin.getText(); // تعيين الحقل ليكون قابل للتحرير

    }//GEN-LAST:event_EnterIDCoachForLoginActionPerformed

    private void EnterPasswordCoachForLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterPasswordCoachForLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterPasswordCoachForLoginActionPerformed

     public void login() {
     
        String FCName="";
        String LCName="";
        String password ="";
        String phoneNumber="";
        boolean found = false;
       try (BufferedReader reader = new BufferedReader(new FileReader("coaches list.txt"))) {
            
            String line;
            while ((line = reader.readLine()) != null) {
                String[] fields = line.split("\\s+");
                if (fields[0].equals(CoachID)) {
                    found = true;
                    FCName = fields[1];
                    LCName = fields[2];
                    password = fields[3];
                    phoneNumber = fields[4];
                 
                  
                    break;
                }
            }

            if (found) {
               
                    if (Password.equals(password)) {
                          LocalDateTime currentTime = LocalDateTime.now();
                          DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEE MMM dd HH:mm:ss yyyy");
                          String formattedTime = currentTime.format(formatter);
                          String message ="Welcome " + FCName + " " + LCName+"<br>"+"You are logged in now at: " + formattedTime ;
            
                          JOptionPane optionPane = new JOptionPane("<html><p style='font-size:14px'>" + message + "</p></html>", JOptionPane.INFORMATION_MESSAGE);
                          JDialog dialog = optionPane.createDialog(null, "Hive Gym");
                          dialog.setSize(715, 370);
                          dialog.setLocationRelativeTo(null);
                          dialog.setLocation(300, 200);
                          setVisible(false);
                          dialog.setVisible(true); // عرض الـ JDialog 
                          GYMJFrame Gym = new GYMJFrame();  
                          Gym.setVisible(true);  
                        
                      
                        
                    } 
                    }
                
             else {
                JOptionPane.showMessageDialog(this, "Sorry, there is no personal identifier like this.");
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "The file you try to access does not exist!!");
        }  
     
     
     
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoachJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EnterIDCoachForLogin;
    private javax.swing.JPasswordField EnterPasswordCoachForLogin;
    private javax.swing.JLabel LabelForCoachPassword;
    private javax.swing.JLabel LabelLoginCoach;
    private javax.swing.JLabel LabelforIDCoach;
    private java.awt.Button backTOGymJFrame;
    private javax.swing.JPanel jPanel1;
    private java.awt.Button loginCoach;
    // End of variables declaration//GEN-END:variables
}
