/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gymapplication;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohammad Alqasem
 */
public class RegisterJFrame extends GymApplication {

    /**
     * Creates new form RegisterJFrame
     */
    public RegisterJFrame() {
        initComponents();
        EnterMemberID.setText(GetID());
          CreateMemberAccountAndLoginToGym.addActionListener(e -> {
            // قم بتحديث المتغيرات من حقول النص قبل استدعاء الدالة login
            fullName = EnterMemberName.getText();
            MemberID = EnterMemberID.getText();
            EnteredPassword = EnterMemberPasword.getText();
            phoneNumber= EnterMemberPhoneNumber.getText();
           numOfMonths = (String) NumberOfMonths.getSelectedItem();
           theCoachNames=(String) CoaceNames.getSelectedItem();
     
             
             String[] words = fullName.trim().split("\\s+");
            int numOFWords =words.length;
          
       
        if(numOFWords<3||numOFWords>3){
            JOptionPane.showMessageDialog(this, "Please enter your Name from 3 digits.");
            return;
        }
        else {
             String[] parts1 = fullName.split(" ");
          
           FName= parts1[0];
           SName=parts1[1];
           LName=parts1[2];

        }
           
           String[]parts2 = theCoachNames.split(" ");
           CName1=parts2[1];
           CName2=parts2[2];
         
           id=MemberID;
           password=EnteredPassword;
             if (id == null || id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Member ID.");
            return;
        }
        if (password == null || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your password.");
            return;
        }
        if (password.length() != 4) {
            EnterMemberPasword.setText("");
            JOptionPane.showMessageDialog(this, "Please enter your password from 4 digits.");
            
            return;
        }
        if(phoneNumber.length()!=10){
            
              JOptionPane.showMessageDialog(this, "Please enter your phone Number from 10 digits.");
              EnterMemberPhoneNumber.setText("");
            return;
        }
        
         
        
        
        
        
           addMember();
        });
    }
   
private String fullName;
private  String MemberID ;
private String password;
private String EnteredPassword;
private String id;
private String FName, SName, LName;
private String phoneNumber;
private int TotalCost=0;//عدد الاشهر
private String numOfMonths;
private String subscription;
private String CName1, CName2;
private String theCoachNames;



    LocalDate currentDate = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String formattedDate = currentDate.format(formatter);
        String[] dateParts = formattedDate.split("/");
        int day = Integer.parseInt(dateParts[0]);
        int month = Integer.parseInt(dateParts[1]);
        int year = Integer.parseInt(dateParts[2]);
        
        
        int ExpDay =Integer.parseInt(dateParts[0]); 
        int ExpMonth= Integer.parseInt(dateParts[1]);
        int ExpYear  = Integer.parseInt(dateParts[2]);



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CreateMemberAccountAndLoginToGym = new java.awt.Button();
        backToMemberJF = new java.awt.Button();
        EnterMemberName = new javax.swing.JTextField();
        LabelMemberName = new javax.swing.JLabel();
        LabelMemberID = new javax.swing.JLabel();
        EnterMemberID = new javax.swing.JTextField();
        LabelMemberPassword = new javax.swing.JLabel();
        LabelPhoneMember = new javax.swing.JLabel();
        EnterMemberPhoneNumber = new javax.swing.JTextField();
        NumberOfMonths = new javax.swing.JComboBox<>();
        LabelNumberOfMonths = new javax.swing.JLabel();
        CoaceNames = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        EnterMemberPasword = new javax.swing.JPasswordField();

        jLabel6.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 57, 66));
        jPanel1.setForeground(new java.awt.Color(26, 41, 62));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register an account");

        CreateMemberAccountAndLoginToGym.setActionCommand("Register_account");
        CreateMemberAccountAndLoginToGym.setBackground(new java.awt.Color(203, 22, 45));
        CreateMemberAccountAndLoginToGym.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CreateMemberAccountAndLoginToGym.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CreateMemberAccountAndLoginToGym.setForeground(new java.awt.Color(255, 255, 255));
        CreateMemberAccountAndLoginToGym.setLabel("Create");
        CreateMemberAccountAndLoginToGym.setName(""); // NOI18N
        CreateMemberAccountAndLoginToGym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateMemberAccountAndLoginToGymActionPerformed(evt);
            }
        });

        backToMemberJF.setActionCommand("Back");
        backToMemberJF.setBackground(new java.awt.Color(203, 22, 45));
        backToMemberJF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backToMemberJF.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        backToMemberJF.setForeground(new java.awt.Color(255, 255, 255));
        backToMemberJF.setLabel("Back");
        backToMemberJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMemberJFActionPerformed(evt);
            }
        });

        EnterMemberName.setBackground(new java.awt.Color(110, 110, 111));
        EnterMemberName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EnterMemberName.setForeground(new java.awt.Color(255, 255, 255));
        EnterMemberName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterMemberNameActionPerformed(evt);
            }
        });

        LabelMemberName.setBackground(new java.awt.Color(110, 110, 111));
        LabelMemberName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelMemberName.setForeground(new java.awt.Color(255, 255, 255));
        LabelMemberName.setText("Name :");

        LabelMemberID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelMemberID.setForeground(new java.awt.Color(255, 255, 255));
        LabelMemberID.setText("ID:");

        EnterMemberID.setEditable(false);
        EnterMemberID.setBackground(new java.awt.Color(110, 110, 111));
        EnterMemberID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EnterMemberID.setForeground(new java.awt.Color(255, 255, 255));
        EnterMemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterMemberIDActionPerformed(evt);
            }
        });

        LabelMemberPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelMemberPassword.setForeground(new java.awt.Color(255, 255, 255));
        LabelMemberPassword.setText("Password:");

        LabelPhoneMember.setBackground(new java.awt.Color(110, 110, 111));
        LabelPhoneMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelPhoneMember.setForeground(new java.awt.Color(255, 255, 255));
        LabelPhoneMember.setText("phone number: ");

        EnterMemberPhoneNumber.setBackground(new java.awt.Color(110, 110, 111));
        EnterMemberPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EnterMemberPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        EnterMemberPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterMemberPhoneNumberActionPerformed(evt);
            }
        });

        NumberOfMonths.setBackground(new java.awt.Color(110, 110, 111));
        NumberOfMonths.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NumberOfMonths.setForeground(new java.awt.Color(255, 255, 255));
        NumberOfMonths.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- one month.      200$", "2- two months.     399$", "3- three months.   590$" }));
        NumberOfMonths.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NumberOfMonthsItemStateChanged(evt);
            }
        });
        NumberOfMonths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberOfMonthsActionPerformed(evt);
            }
        });

        LabelNumberOfMonths.setBackground(new java.awt.Color(110, 110, 111));
        LabelNumberOfMonths.setForeground(new java.awt.Color(255, 255, 255));
        LabelNumberOfMonths.setText("Number of months:");

        CoaceNames.setBackground(new java.awt.Color(110, 110, 111));
        CoaceNames.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CoaceNames.setForeground(new java.awt.Color(255, 255, 255));
        CoaceNames.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01- None Coach           000$", "02- Ahmad ALali          100$", "03- Omar Khaled          150$", "04- Chris Bum               900$", "05- Naser Yaqoob          70$", "06- Bilal Ahmad           200$ ", "07- Arnold Alois           250$", "08- Ronnie Coleman    300$", "09- Rania Mahmood    500$", "10- Captain Janti          100$", "11- Big Rami                350$" }));
        CoaceNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoaceNamesActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(110, 110, 111));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Train with: ");

        EnterMemberPasword.setBackground(new java.awt.Color(110, 110, 111));
        EnterMemberPasword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EnterMemberPasword.setForeground(new java.awt.Color(255, 255, 255));
        EnterMemberPasword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EnterMemberPasword.setToolTipText("*");
        EnterMemberPasword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterMemberPaswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelPhoneMember)
                        .addGap(0, 0, 0)
                        .addComponent(EnterMemberPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(EnterMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelNumberOfMonths, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(NumberOfMonths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(EnterMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelMemberPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(EnterMemberPasword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CoaceNames, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backToMemberJF, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreateMemberAccountAndLoginToGym, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EnterMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnterMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelMemberPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EnterMemberPasword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelPhoneMember, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EnterMemberPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelNumberOfMonths, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NumberOfMonths, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoaceNames, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateMemberAccountAndLoginToGym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(backToMemberJF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateMemberAccountAndLoginToGymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateMemberAccountAndLoginToGymActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateMemberAccountAndLoginToGymActionPerformed

    private void backToMemberJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMemberJFActionPerformed
        // TODO add your handling code here:
         MemberJFrame mem = new MemberJFrame();  
      mem.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backToMemberJFActionPerformed

    private void EnterMemberNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterMemberNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterMemberNameActionPerformed

    private void EnterMemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterMemberIDActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_EnterMemberIDActionPerformed

    private void EnterMemberPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterMemberPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterMemberPhoneNumberActionPerformed

    private void NumberOfMonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberOfMonthsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberOfMonthsActionPerformed

    private void NumberOfMonthsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NumberOfMonthsItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberOfMonthsItemStateChanged

    private void CoaceNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoaceNamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CoaceNamesActionPerformed

    private void EnterMemberPaswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterMemberPaswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterMemberPaswordActionPerformed

  
    public void addMember() {
       
    System.out.println(phoneNumber);

        
         
        
      currentDate = LocalDate.now();
          
            
            if (numOfMonths.equals("1- one month.      200$")) {
                       ExpMonth = currentDate.plusMonths(1).getMonthValue();
                       TotalCost+=200;
                       }

            else if (numOfMonths.equals("2- two months.     399$")) {
                 ExpMonth = currentDate.plusMonths(2).getMonthValue();
                  TotalCost+=399;
            }
            
            else if (numOfMonths.equals("3- three months.   590$")) {
    ExpMonth = currentDate.plusMonths(3).getMonthValue();
     TotalCost+=590;
      }
            
           
        if ( CName1 == "None"){
            subscription="public";
                     }
        else {
               subscription="private";
        }
        /*
        
        01- None Coach           000$
02- Ahmad ALali          100$
03- Omar Khaled          150$
04- Chris Bum               900$
05- Naser Yaqoob          70$
06- Bilal Ahmad           200$ 
07- Arnold Alois           250$
08- Ronnie Coleman    300$
09- Rania Mahmood    500$
10- Captain Janti          100$
11- Big Rami                350$
        */
        switch(CName1+" "+CName2){
            case "Ahmad ALali":
                TotalCost+=100;
                 break;
            case "Omar Khaled":
                TotalCost+=150;
                 break;
            case "Chris Bum":
                TotalCost+=900;
                 break;
            case "Naser Yaqoob":
                TotalCost+=70;
                 break;
            case "Bilal Ahmad":
                TotalCost+=200;
                 break;
            case "Arnold Alois":
                TotalCost+=250;
                 break;
            case "Ronnie Coleman":
                TotalCost+=300;
                 break;
            case "Rania Mahmood":
                TotalCost+=500;
                 break;
            case "Captain Janti":
                TotalCost+=100;
                 break;
            case "Big Rami":
                TotalCost+=350;
                 break;
                 
            
        }
        
        
      BufferedWriter myfile = null;
try {
    myfile = new BufferedWriter(new FileWriter("Members list.txt", true));
    if (myfile != null) {
        myfile.write(id + "  \t" + FName + " " + SName + " " + LName + "        \t" + password + "   \t" + phoneNumber + "   \t" + subscription + "     \t " + CName1 + " " + CName2 + "   \t   " + year + " " + month + " " + day + "   \t   " + ExpYear + " " + ExpMonth + " " +ExpDay);
        myfile.newLine();
        myfile.flush();
        
        
          String message = "                The adding was completed successfully :)"+"<br>" +"<br>" +"Welcome " + FName + " " + SName + " " + LName + "<br>" + "Your ID:" + id+
            "<br>" +
            "Your phone number: " + phoneNumber + "<br>" + "Your coach name: " + CName1 + " " + CName2+"<br>" +"<br>" +"Total Cost: "+TotalCost+"$";
        
        JOptionPane optionPane = new JOptionPane("<html><p style='font-size:14px'>" + message + "</p></html>", JOptionPane.INFORMATION_MESSAGE);
    JDialog dialog = optionPane.createDialog(null, "Hive Gym");
    dialog.setSize(715, 370);
    dialog.setLocationRelativeTo(null);
    dialog.setLocation(300, 200);
    
    
         setVisible(false);
    dialog.setVisible(true); // عرض الـ JDialog 
     GYMJFrame Gym = new GYMJFrame();  
      Gym.setVisible(true);
        
        System.out.println("The adding was completed successfully :)");
    } else {
        System.out.println("The file you are trying to access does not exist!");
    }
} catch (IOException e) {
    e.printStackTrace();
} finally {
    if (myfile != null) {
        try {
            myfile.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
        
        
        
 
 
        }
       
String GetID() {
    try (BufferedReader reader = new BufferedReader(new FileReader("Members list.txt"))) {
        String line;
        while ((line = reader.readLine()) != null) {
            String[] fields = line.split("\\s+");
            id = fields[0];
        }
        
        if (id != null && !id.isEmpty()) {
            int LastID = Integer.parseInt(id) + 1;
            String NewID = String.valueOf(LastID);
            return NewID;
        } else {
            
            return "error: empty id";
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "The file you try to access does not exist!! ");
    }

    return "error: file not found";
}
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CoaceNames;
    private java.awt.Button CreateMemberAccountAndLoginToGym;
    private javax.swing.JTextField EnterMemberID;
    private javax.swing.JTextField EnterMemberName;
    private javax.swing.JPasswordField EnterMemberPasword;
    private javax.swing.JTextField EnterMemberPhoneNumber;
    private javax.swing.JLabel LabelMemberID;
    private javax.swing.JLabel LabelMemberName;
    private javax.swing.JLabel LabelMemberPassword;
    private javax.swing.JLabel LabelNumberOfMonths;
    private javax.swing.JLabel LabelPhoneMember;
    private javax.swing.JComboBox<String> NumberOfMonths;
    private java.awt.Button backToMemberJF;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
